Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -34,20 +34,20 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          if (Test-Path "$env:GITHUB_WORKSPACE\yarn.lock") {
+              echo "manager=yarn" >> $env:GITHUB_OUTPUT
+              echo "command=install" >> $env:GITHUB_OUTPUT
+              echo "runner=yarn" >> $env:GITHUB_OUTPUT
+              exit 0
+          } elseif (Test-Path "$env:GITHUB_WORKSPACE\package.json") {
+              echo "manager=npm" >> $env:GITHUB_OUTPUT
+              echo "command=ci" >> $env:GITHUB_OUTPUT
+              echo "runner=npx --no-install" >> $env:GITHUB_OUTPUT
+              exit 0
+          } else {
+              echo "Unable to determine package manager"
+              exit 1
+          }
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
